### ISSUE TITLE
Can't setup Shutdown and Poweroff on RPi5

### ISSUE THREAD

**Issue by CaptIgmu** [openplotter/openplotter-settings#29]
On **_RPi5_**, can't setup **_Shutdown/Poweroff_** in **_Raspberry Settings_** because **_GPIO Map only shows 35 pins_**, so can't select GPIO 21 (pin 40) or GPIO 26 (pin 37). Can't manually enter a number, have to pick from GPIO Map. (I am using a MacArthur HAT)

**Comment by sailoog** [comment]
Screen size? could you send an screenshot?

**Comment by CaptIgmu** [comment]
Screenshot at 1680 x 1050 but also same appearance with lower or higher resolution screen:
![SettingsRPi5_1680x1050](https://github.com/user-attachments/assets/6d7a11c7-3eaf-4e39-9815-bebee73fdbba)

**Comment by sailoog** [comment]
Ok, I see you are on Wayland. OpenPlotter is optimized for X11 because Wayland is not mature yet and there are unexpected behaviors like this. We can not make that window bigger because it has to fit in 7" on X11, so I have added a scroller in openplotter-settings v 4.2.6, please test.

Update the entire system:
```
sudo apt update
sudo apt full-upgrade
```
You will probably find more problems on Wayland, especially on OpenCPN and Raspberry OS native menus.

**Comment by CaptIgmu** [comment]
Yihaa! That works in v4.2.6    Thanks!

**Comment by sailoog** [comment]
Perfect, thanks for reporting.
